### ISSUE TITLE
Ideia do jogo

### ISSUE THREAD

**Issue by fspacheco** [pedro-rb/JogoC#1]
Como solicitado no cronograma, favor incluir definição geral do jogo (ideia) em um documento **proposta-geral.md**
Depois, fechar essa _issue_

**Comment by fspacheco** [comment]
O arquivo não foi incluído no repositório

**Comment by pedro-rb** [comment]
Arrumado

**Comment by fspacheco** [comment]
Ok. Precisa agora desenvolver a ideia e deixar mais claro o aspecto educacional. Consultoria vai ajudar.
